version: '3.1'
services:
  calculator-server:
    build: .
    image: calculator-server
    container_name: calculator-server
    ports:
      - "8080:8080"
    depends_on:
      - calculator-db
    environment:
      - POSTGRES_DATASOURCE_URL=jdbc:postgresql://calculator-db:5432/calculatordb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  calculator-db:
    image: postgres:14-alpine
    container_name: calculator-db
    ports:
      - "6543:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=calculatordb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root